export const Categories = [
  {
    name: 'Grocery & Kitchen',
    subCategory: [
      {
        name: 'Vegetable & Fruits',
        image: require('../assets/images/Categories/Grocery/NewFolder/vegandfruits.png'),
      },
      {
        name: 'Atta,Rice & Dal',
        image: require('../assets/images/Categories/Grocery/NewFolder/attaricedal.png'),
      },
      {
        name: 'Oil,Ghee & Masala',
        image: require('../assets/images/Categories/Grocery/NewFolder/oilGheeMasala.png'),
      },
      {
        name: 'Daily Bread',
        image: require('../assets/images/Categories/Grocery/NewFolder/dairyEggsBread.png'),
      },
      {
        name: 'Bakery & Biscuit',
        image: require('../assets/images/Categories/Grocery/NewFolder/biscuits.png'),
      },
      {
        name: 'Dry Fruits & Cereals',
        image: require('../assets/images/Categories/Grocery/NewFolder/dryFruitsCerals.png'),
      },
      {
        name: 'Kitchenware & Appliances',
        image: require('../assets/images/Categories/Grocery/NewFolder/kitchenware.png'),
      },
    ],
  },
  {
    name: 'Snacks & Kitchen',
    subCategory: [
      {
        name: 'Chips & Namkeens',
        image: require('../assets/images/Categories/snacks/Newfolder/namkeen.png'),
      },
      {
        name: 'Sweets & Chocolates',
        image: require('../assets/images/Categories/snacks/Newfolder/sweetsChocolates.png'),
      },
      {
        name: 'Drinks & Juices',
        image: require('../assets/images/Categories/snacks/Newfolder/drinksJuices.png'),
      },
      {
        name: 'Tea, Coffee & Milk drinks',
        image: require('../assets/images/Categories/snacks/Newfolder/teaDrinks.png'),
      },
      {
        name: 'Instant Food',
        image: require('../assets/images/Categories/snacks/Newfolder/instantFoods.png'),
      },
      {
        name: 'Sauces & Spreads',
        image: require('../assets/images/Categories/snacks/Newfolder/sauces.png'),
      },
      {
        name: 'Paan Corner',
        image: require('../assets/images/Categories/snacks/Newfolder/resized_paancorner.jpg'),
      },
    ],
  },
  {
    name: 'Beauty & Personal Care',
    subCategory: [
      {
        name: 'Bath & Body',
        image: require('../assets/images/Categories/bath&body/Newfolder/bathBody.png'),
      },
      {
        name: 'Hair',
        image: require('../assets/images/Categories/bath&body/Newfolder/hair.png'),
      },
      {
        name: 'Skin & face',
        image: require('../assets/images/Categories/bath&body/Newfolder/skincare.png'),
      },
      {
        name: 'Beauty & Cosmetics',
        image: require('../assets/images/Categories/bath&body/Newfolder/beautyCosmetics.png'),
      },
      {
        name: 'Feminine Hygiene',
        image: require('../assets/images/Categories/bath&body/Newfolder/feminine.png'),
      },
      {
        name: 'Baby Care',
        image: require('../assets/images/Categories/bath&body/Newfolder/babycare.png'),
      },
      {
        name: 'Health & Pharma',
        image: require('../assets/images/Categories/bath&body/Newfolder/healthPharma.png'),
      },
    ],
  },
  {
    name: 'Household Essentials',
    subCategory: [
      {
        name: 'Cleaners & Repellents',
        image: require('../assets/images/Categories/household/Newfolder/resized_Cleaners&Repellents.webp'),
      },
      {
        name: 'Stationary & Games',
        image: require('../assets/images/Categories/household/Newfolder/Resized_PencilPen&Markers.jpg'),
      },
    ],
  },
];

export const SubCategories = {
  'Vegetable & Fruits': [
    'Fresh Vegetables',
    'Fresh Fruits',
    // 'Coriander & Other',
    'Exotics',
    // 'Mangoes & Melons',
    // 'Seasonal',
    // 'Flower & Leaves',
    // 'Freshly Cut Sprouts',
    'Frozen Veg',
    // 'Certified Organic',
    // 'Hydrophonic',
  ],
  'Atta,Rice & Dal': [
    'Fresh Vegetables',
    'Fresh Fruits',
    'Coriander & Other',
    'Exotics',
    'Mangoes & Melons',
    'Seasonal',
    'Flower & Leaves',
    'Freshly Cut Sprouts',
    'Frozen Veg',
    'Certified Organic',
    'Hydrophonic',
  ],
  'Oil, Ghee & Masala': [
    'Desi Ghee',
    // 'A2 & Cow Ghee',
    'Powder & Spices',
    'Salt, Sugar & Jaggery',
    'Whole Spices',
    'Herbs & Seasoning',
    'Organic',
  ],
  'Daily Bread': [
    'Milk',
    'Bread & Pav',
    // 'Curd & Youghurt',
    'Cheese & Butter',
    'Paneer & Tofu',
    'Lassi & Milkshake',
    'Cream & Whitener',
  ],
  'Bakery & Biscuit': [
    'Cookies',
    'Cream Biscuit',
    'Healthy & Digestive',
    'Sweet & Salty',
    'Glucose & Marie',
    'Rusks & Wafers',
    'Cakes & Rolls',
    'Baking Ingredients',
    // 'Gourmet Bakery',
    // 'Biscuit Gift Pack',
  ],
  'Dry Fruits & Cereals': [
    'Dry Fruit',
    'Dry Fruit Snacks',
    'Corn Flakes & Kids Cereals',
    'Muesli & Granola',
    // 'Oats & Daliya',
    'Dates & Seeds',
    'Vermicelli & Poha',
    'Organic & Premium',
    'Dry Fruit Gift Pack',
  ],
  'Kitchenware & Appliances': ['Tissues & Disposals'],
  'Chips & Namkeens': [
    'Chips & Wafers',
    'Bhujia & Mixture',
    'Namkeens Snacks',
    'Nachos',
    'Healthy Snacks',
    'Popcorn',
    'Papads & Fryums',
    'Premium',
    // 'Gift Pack',
  ],
  'Sweets & Chocolates': [
    'Chocolates',
    'Candies & Gum',
    'Chocolate Packs',
    'Indian Sweets',
    'Syrups',
    'Premium',
    'Chocolate Gift Pack',
    // 'Energy Bars',
  ],
  'Drinks & Juices': [
    'Soft Drinks',
    'Fruits Juices',
    'Energy Drinks',
    // 'Soda & Mixture',
    'Water & Ice Cubes',
    'Mango Drinks',
    'Cold Coffee & Ice Tea',
    // 'Coconut Water',
    'Conentrate & Syrups',
    'Premium',
    'Beverages & Gift Packs',
  ],
  'Tea, Coffee & Milk drinks': [
    'Tea',
    'Coffee',
    'Hot Chocolate',
    'Green Tea',
    'Milk drinks',
    'Cold Coffee & Iced Tea',
    'Bags & Premixes',
    'Premium',
  ],
  'Instant Food': [
    'Noodles',
    'Pasta',
    'Frozen Veg Snacks',
    'Ready To Eat',
    'Idli & Dosa Batter',
    'Soup',
    'Dessert & Cake Mixes',
    // 'Organic & Premium',
    'Energy Bars',
  ],
  'Sauces & Spreads': [
    'Tomato Ketchup',
    'Asian Sauces',
    'Jam & Spreads',
    'Mayonnaise',
    'Peanut Butter',
    'Chyawanprash & Honey',
    'Chutney & Pickel',
    'Salad Dressings',
    'Dips',
    'Cooking Sauces',
    'Premium',
  ],
  'Paan Corner': [
    'Rolling Paper',
    'Hookah Needs',
    'Hookah Flavour',
    'Paan',
    'Mouth Freshener',
    'Smoking Cessation',
  ],
  'Ice Cream & More': [
    'Tubs',
    'Sticks',
    'Cones',
    'Cassata & Sandwich',
    'Single Serve Cups',
    'Guilt-Free',
    'Gourmet',
  ],
  'Bath & Body': ['Bath Wash'],
  // eslint-disable-next-line prettier/prettier
  Hair: ['Shampoo'],
  'Skin & Face': ['Sunscreen'],
  'Beauty & Cosmetics': [],
  'Feminine Hygiene': [],
  'Baby Care': [],
  'Health & Pharma': [],
  'Sexual Wellness': [],
  'Home & Lifestyle': [],
  'Cleaners & Repellents': [],
  // eslint-disable-next-line prettier/prettier
  Electronics: [],
  'Stationary & Games': [],
};

export const hideCategories = [
  'mangos & melons',
  'hydrophonic',
  'coriander & other',
  'certified organic',
  'freshly cut sprouts',
  'flower & leaves',
  'seasonal',
  'organic',
  'organic species',
  'Curd & youghurt',
  'biscuit gift pack',
  'gourmet bakery',
  'oats & daliya',
  'gift pack',
  'energy bars',
  'soda & mixture',
  'coconut water',
  'Hot chocolate',
  'organic & premium',
  'smoking cessation',
  'honey & chwanparash',
  'vitamins & supplements',
  'health care equipment',
  'Machine and car care',
];
