
export const Categories = [
  {
    name: 'Grocery & Kitchen',
    subCategory: [
      {
        name: 'Vegetable & Fruits',
        image: 'https://ik.imagekit.io/vnpzydnah/kasera-Store/veg_and_fruits_UHvmbX482.jpg',
      },
      {
        name: 'Atta, Rice & Dal',
        image: 'https://ik.imagekit.io/vnpzydnah/kasera-Store/Atta_Rice_and_dal_oh1A8I0zb.jpg',
      },
      {
        name: 'Oil, Ghee & Masala',
        image: 'https://ik.imagekit.io/vnpzydnah/kasera-Store/oil_ghee_XHnB1wpBBm.jpg',
      },
      {
        name: 'Daily Bread',
        image: 'https://ik.imagekit.io/vnpzydnah/kasera-Store/daily_bread_EBZHmzVr9.jpg',
      },
      {
        name: 'Bakery & Biscuit',
        image: 'https://ik.imagekit.io/vnpzydnah/kasera-Store/bakery___Biscuit_rU-mBOF2u.jpg',
      },
      {
        name: 'Dry Fruits & Cereals',
        image: 'https://ik.imagekit.io/vnpzydnah/kasera-Store/dry_fruit_XN-58-_U5.jpg',
      },
      {
        name: 'Kitchenware & Appliances',
        image: 'https://ik.imagekit.io/vnpzydnah/kasera-Store/kitchenware_FgnQffOD-.png',
      },
    ],
  },
  {
    name: 'Snacks & Kitchen',
    subCategory: [
      {
        name: 'Chips & Namkeens',
        image: 'https://ik.imagekit.io/vnpzydnah/kasera-Store/Chips___Namkeen_f1bA2pMII.png',
      },
      {
        name: 'Sweets & Chocolates',
        image: 'https://ik.imagekit.io/vnpzydnah/kasera-Store/Sweets___Chocolates_Wizqh9Z2v.png',
      },
      {
        name: 'Drinks & Juices',
        image: 'https://ik.imagekit.io/vnpzydnah/kasera-Store/Drinks___Juices_GqUYQJm1Q.webp',
      },
      {
        name: 'Tea, Coffee & Milk drinks',
        image: 'https://ik.imagekit.io/vnpzydnah/kasera-Store/Tea__Coffee___Mik_NEKeg9yUp.webp',
      },
      {
        name: 'Instant Food',
        image: 'https://ik.imagekit.io/vnpzydnah/kasera-Store/Instant_food_aCvSshhbK.jpg',
      },
      {
        name: 'Sauces & Spreads',
        image: 'https://ik.imagekit.io/vnpzydnah/kasera-Store/sauces___spreads_L35RYiU0Mi.webp',
      },
      {
        name: 'Paan Corner',
        image: 'https://ik.imagekit.io/vnpzydnah/kasera-Store/paan_corner_3_sOdZ2rv6.jpg',
      },
    ],
  },
  {
    name: 'Beauty & Personal Care',
    subCategory: [
      {
        name: 'Bath & Body',
        image: 'https://ik.imagekit.io/vnpzydnah/kasera-Store/bath_and_Body_VakLOIWEP.jpg',
      },
      {
        name: 'Hair',
        image: 'https://ik.imagekit.io/vnpzydnah/kasera-Store/hair_accessories_xcJm9zvxsE.jpg',
      },
      {
        name: 'Skin & face',
        image: "https://ik.imagekit.io/vnpzydnah/kasera-Store/Skin___Face_QeoEVpcAv6.png",
      },
      {
        name: 'Beauty & Cosmetics',
        image: "https://ik.imagekit.io/vnpzydnah/kasera-Store/Beauty___Cosmetics_7J4rk3fHe.webp",
      },
      {
        name: 'Feminine Hygiene',
        image: "https://ik.imagekit.io/vnpzydnah/kasera-Store/Female_Hygine_FUf9AGc7O.jpg",
      },
      {
        name: 'Baby Care',
        image: "https://ik.imagekit.io/vnpzydnah/kasera-Store/Female_Hygine_FUf9AGc7O.jpg",
      },
      {
        name: 'Health & Pharma',
        image: "https://ik.imagekit.io/vnpzydnah/kasera-Store/Health___Pharma_pY3INJJd8.webp",
      },
    ],
  },
  {
    name: 'Household Essentials',
    subCategory: [
      {
        name: 'Cleaners & Repellents',
        image: "https://ik.imagekit.io/vnpzydnah/kasera-Store/Health___Pharma_pY3INJJd8.webp",
      },
      {
        name: 'Stationary & Games',
        image: "https://ik.imagekit.io/vnpzydnah/kasera-Store/Health___Pharma_pY3INJJd8.webp",
      },
    ],
  },
];

export const SubCategories = {
  'Vegetable & Fruits': [
    'Fresh Vegetables',
    'Fresh Fruits',
    'Coriander & Other',
    'Exotics',
    'Mangoes & Melons',
    'Seasonal',
    'Flower & Leaves',
    'Freshly Cut Sprouts',
    'Frozen Veg',
    'Certified Organic',
    'Hydrophonic',
  ],
  'Atta, Rice & Dal': [
    'Fresh Vegetables',
    'Fresh Fruits',
    'Coriander & Other',
    'Exotics',
    'Mangoes & Melons',
    'Seasonal',
    'Flower & Leaves',
    'Freshly Cut Sprouts',
    'Frozen Veg',
    'Certified Organic',
    'Hydrophonic',
  ],
  'Oil, Ghee & Masala': [
    'Desi Ghee',
    'A2 & Cow Ghee',
    'Powder & Spices',
    'Salt, Sugar & Jaggery',
    'Whole Spices',
    'Herbs & Seasoning',
    'Organic',
  ],
  'Daily Bread': [
    'Milk',
    'Bread & Pav',
    'Curd & Youghurt',
    'Cheese & Butter',
    'Paneer & Tofu',
    'Lassi & Milkshake',
    'Cream & Whitener',
  ],
  'Bakery & Biscuit': [
    'Cookies',
    'Cream Biscuit',
    'Healthy & Digestive',
    'Sweet & Salty',
    'Glucose & Marie',
    'Rusks & Wafers',
    'Cakes & Rolls',
    'Baking Ingredients',
    'Gourmet Bakery',
    'Biscuit Gift Pack',
  ],
  'Dry Fruits & Cereals': [
    'Dry Fruit',
    'Dry Fruit Snacks',
    'Corn Flakes & Kids Cereals',
    'Muesli & Granola',
    'Oats & Daliya',
    'Dates & Seeds',
    'Vermicelli & Poha',
    'Organic & Premium',
    'Dry Fruit Gift Pack',
  ],
  'Kitchenware & Appliances': ['Tissues & Disposals'],
  'Chips & Namkeens': [
    'Chips & Wafers',
    'Bhujia & Mixture',
    'Namkeens Snacks',
    'Nachos',
    'Healthy Snacks',
    'Popcorn',
    'Papads & Fryums',
    'Premium',
    'Gift Pack',
  ],
  'Sweets & Chocolates': [
    'Chocolates',
    'Candies & Gum',
    'Chocolate Packs',
    'Indian Sweets',
    'Syrups',
    'Premium',
    'Chocolate Gift Pack',
    'Energy Bars',
  ],
  'Drinks & Juices': [
    'Soft Drinks',
    'Fruits Juices',
    'Energy Drinks',
    'Soda & Mixture',
    'Water & Ice Cubes',
    'Mango Drinks',
    'Cold Coffee & Ice Tea',
    'Coconut Water',
    'Conentrate & Syrups',
    'Premium',
    'Beverages & Gift Packs',
  ],
  'Tea, Coffee & Milk drinks': [
    'Tea',
    'Coffee',
    'Hot Chocolate',
    'Green Tea',
    'Milk drinks',
    'Cold Coffee & Iced Tea',
    'Bags & Premixes',
    'Premium',
  ],
  'Instant Food': [
    'Noodles',
    'Pasta',
    'Frozen Veg Snacks',
    'Ready To Eat',
    'Idli & Dosa Batter',
    'Soup',
    'Dessert & Cake Mixes',
    'Organic & Premium',
    'Energy Bars',
  ],
  'Sauces & Spreads': [
    'Tomato Ketchup',
    'Asian Sauces',
    'Jam & Spreads',
    'Mayonnaise',
    'Peanut Butter',
    'Chyawanprash & Honey',
    'Chutney & Pickel',
    'Salad Dressings',
    'Dips',
    'Cooking Sauces',
    'Premium',
  ],
  'Paan Corner': [
    'Rolling Paper',
    'Hookah Needs',
    'Hookah Flavour',
    'Paan',
    'Mouth Freshener',
    'Smoking Cessation',
  ],
  'Ice Cream & More': [
    'Tubs',
    'Sticks',
    'Cones',
    'Cassata & Sandwich',
    'Single Serve Cups',
    'Guilt-Free',
    'Gourmet',
  ],
  'Bath & Body': ['Bath Wash'],
  // eslint-disable-next-line prettier/prettier
  Hair: ['Shampoo'],
  'Skin & Face': ['Sunscreen'],
  'Beauty & Cosmetics': [],
  'Feminine Hygiene': [],
  'Baby Care': [],
  'Health & Pharma': [],
  'Sexual Wellness': [],
  'Home & Lifestyle': [],
  'Cleaners & Repellents': [],
  // eslint-disable-next-line prettier/prettier
  Electronics: [],
  'Stationary & Games': [],
};
