export const Categories = {
  'Grocery & Kitchen': [
    {
      subCategory: 'Vegetable & Fruits',
      image: require('../assets/images/Categories/fruits_veg.png'),
    },
    {
      subCategory: 'Atta, Rice & Dal',
      image: require('../assets/images/Categories/Atta_rice.png'),
    },
    {
      subCategory: 'Oil, Ghee & Masala',
      image: require('../assets/images/Categories/oil_ghee.png'),
    },
    {
      subCategory: 'Daily Bread',
      image: require('../assets/images/Categories/daily_bread.png'),
    },
    {
      subCategory: 'Bakery & Biscuit',
      image: require('../assets/images/Categories/bakery.png'),
    },
    {
      subCategory: 'Dry Fruits & Cereals',
      image: require('../assets/images/Categories/dry_fruits.png'),
    },
    {
      subCategory: 'Kitchenware & Appliances',
      image: require('../assets/images/Categories/kitchen.png'),
    },
  ],
  'Snacks & Kitchen': [
    {
      subCategory: 'Chips & Namkeens',
      image: require('../assets/images/Categories/chips.png'),
    },
    {
      subCategory: 'Sweets & Chocolates',
      image: require('../assets/images/Categories/sweet_chocolate.png'),
    },
    {
      subCategory: 'Drinks & Juices',
      image: require('../assets/images/Categories/drinks.png'),
    },
    {
      subCategory: 'Tea, Coffee & Milk drinks',
      image: require('../assets/images/Categories/Tea.png'),
    },
    {
      subCategory: 'Instant Food',
      image: require('../assets/images/Categories/instant_food.png'),
    },
    {
      subCategory: 'Sauces & Spreads',
      image: require('../assets/images/Categories/sauces.png'),
    },
    {
      subCategory: 'Paan Corner',
      image: require('../assets/images/Categories/paan_corner.png'),
    },
    {
      subCategory: 'Ice Cream & More',
      image: require('../assets/images/Categories/icecream.png'),
    },
  ],
  'Beauty & Personal Care': [
    {
      subCategory: 'Bath & Body',
      image: require('../assets/images/Categories/Bath_body.png'),
    },
    {
      subCategory: 'Hair',
      image: require('../assets/images/Categories/hair.png'),
    },
    {
      subCategory: 'Skin & face',
      image: require('../assets/images/Categories/skin_face.png'),
    },
    {
      subCategory: 'Beauty & Cosmetics',
      image: require('../assets/images/Categories/beauty_cosmetics.png'),
    },
    {
      subCategory: 'Feminine Hygiene',
      image: require('../assets/images/Categories/female_hygiene.png'),
    },
    {
      subCategory: 'Baby Care',
      image: require('../assets/images/Categories/baby_care.png'),
    },
    {
      subCategory: 'Health & Pharma',
      image: require('../assets/images/Categories/Health_pharma.png'),
    },
    {
      subCategory: 'Sexual Wellness',
      image: require('../assets/images/Categories/sexual_wellness.png'),
    },
  ],
  'Household Essentials': [
    {
      subCategory: 'Home & Lifestyle',
      image: require('../assets/images/Categories/home_lifestyle.png'),
    },
    {
      subCategory: 'Cleaners & Repellents',
      image: require('../assets/images/Categories/cleaner_repellents.png'),
    },
    {
      subCategory: 'Electronics',
      image: require('../assets/images/Categories/electronics.png'),
    },
    {
      subCategory: 'Stationary & Games',
      image: require('../assets/images/Categories/stationary.png'),
    },
  ],
};

export const SubCategories = {
  'Vegetable & Fruits': [
    'Fresh Vegetables',
    'Fresh Fruits',
    'Coriander & Other',
    'Exotics',
    'Mangoes & Melons',
    'Seasonal',
    'Flower & Leaves',
    'Freshly Cut Sprouts',
    'Frozen Veg',
    'Certified Organic',
    'Hydrophonic',
  ],
  'Atta, Rice & Dal': [
    'Fresh Vegetables',
    'Fresh Fruits',
    'Coriander & Other',
    'Exotics',
    'Mangoes & Melons',
    'Seasonal',
    'Flower & Leaves',
    'Freshly Cut Sprouts',
    'Frozen Veg',
    'Certified Organic',
    'Hydrophonic',
  ],
  'Oil, Ghee & Masala': [
    'Desi Ghee',
    'A2 & Cow Ghee',
    'Powder & Spices',
    'Salt, Sugar & Jaggery',
    'Whole Spices',
    'Herbs & Seasoning',
    'Organic',
  ],
  'Daily Bread': [
    'Milk',
    'Bread & Pav',
    'Curd & Youghurt',
    'Cheese & Butter',
    'Paneer & Tofu',
    'Lassi & Milkshake',
    'Cream & Whitener',
  ],
  'Bakery & Biscuit': [
    'Cookies',
    'Cream Biscuit',
    'Healthy & Digestive',
    'Sweet & Salty',
    'Glucose & Marie',
    'Rusks & Wafers',
    'Cakes & Rolls',
    'Baking Ingredients',
    'Gourmet Bakery',
    'Biscuit Gift Pack',
  ],
  'Dry Fruits & Cereals': [
    'Dry Fruit',
    'Dry Fruit Snacks',
    'Corn Flakes & Kids Cereals',
    'Muesli & Granola',
    'Oats & Daliya',
    'Dates & Seeds',
    'Vermicelli & Poha',
    'Organic & Premium',
    'Dry Fruit Gift Pack',
  ],
  'Kitchenware & Appliances': ['Tissues & Disposals'],
  'Chips & Namkeens': [
    'Chips & Wafers',
    'Bhujia & Mixture',
    'Namkeens Snacks',
    'Nachos',
    'Healthy Snacks',
    'Popcorn',
    'Papads & Fryums',
    'Premium',
    'Gift Pack',
  ],
  'Sweets & Chocolates': [
    'Chocolates',
    'Candies & Gum',
    'Chocolate Packs',
    'Indian Sweets',
    'Syrups',
    'Premium',
    'Chocolate Gift Pack',
    'Energy Bars',
  ],
  'Drinks & Juices': [
    'Soft Drinks',
    'Fruits Juices',
    'Energy Drinks',
    'Soda & Mixture',
    'Water & Ice Cubes',
    'Mango Drinks',
    'Cold Coffee & Ice Tea',
    'Coconut Water',
    'Conentrate & Syrups',
    'Premium',
    'Beverages & Gift Packs',
  ],
  'Tea, Coffee & Milk drinks': [
    'Tea',
    'Coffee',
    'Hot Chocolate',
    'Green Tea',
    'Milk drinks',
    'Cold Coffee & Iced Tea',
    'Bags & Premixes',
    'Premium',
  ],
  'Instant Food': [
    'Noodles',
    'Pasta',
    'Frozen Veg Snacks',
    'Ready To Eat',
    'Idli & Dosa Batter',
    'Soup',
    'Dessert & Cake Mixes',
    'Organic & Premium',
    'Energy Bars',
  ],
  'Sauces & Spreads': [
    'Tomato Ketchup',
    'Asian Sauces',
    'Jam & Spreads',
    'Mayonnaise',
    'Peanut Butter',
    'Chyawanprash & Honey',
    'Chutney & Pickel',
    'Salad Dressings',
    'Dips',
    'Cooking Sauces',
    'Premium',
  ],
  'Paan Corner': [
    'Rolling Paper',
    'Hookah Needs',
    'Hookah Flavour',
    'Paan',
    'Mouth Freshener',
    'Smoking Cessation',
  ],
  'Ice Cream & More': [
    'Tubs',
    'Sticks',
    'Cones',
    'Cassata & Sandwich',
    'Single Serve Cups',
    'Guilt-Free',
    'Gourmet',
  ],
  'Bath & Body': ['Bath Wash'],
  // eslint-disable-next-line prettier/prettier
  Hair: ['Shampoo'],
  'Skin & Face': ['Sunscreen'],
  'Beauty & Cosmetics': [],
  'Feminine Hygiene': [],
  'Baby Care': [],
  'Health & Pharma': [],
  'Sexual Wellness': [],
  'Home & Lifestyle': [],
  'Cleaners & Repellents': [],
  // eslint-disable-next-line prettier/prettier
  Electronics: [],
  'Stationary & Games': [],
};
