export const API = {
  LOGIN: '/send-otp',
  VERIFY_OTP: '/verify-otp',
  SIGNUP:'/signup',
  GET_PRODUCTS:'/product/list',
  FETCH_USER_DATA:'/profile/user/fetch',
  UPDATE_USER_DATA:'/profile/user/update',
  GET_ADDRESS:'/profile/address/fetch',
  ADD_ADDRESS:'/profile/address/add',
  UPDATE_ADDRESS:'/profile/address/update',
  DELETE_ADDRESS:'/profile/address/delete',
  CREATE_SUGGESTION:'/suggestion/create',
  GET_ORDER:'/order/list',
  CREATE_ORDER:'/order/create',
  FETCH_PAYMENT:'/payment/get/payment-link?amount',
  PAYMENT_STATUS:'/payment/status?paymentId',
  FETCH_ALL_CATEGORY:'/category/all',
  EVALUATE_ORDERS:'/order/evaluate',
};
