export const Routes = {
  Login: 'Login',
  Otp: "otp",
  Signup: 'Signup',
  Home: 'Home',
  Settings: 'Settings',
  Orders: 'My Orders',
  AddressBook: 'Addresses',
  Profile: 'Profile',
  SuggestProduct: 'Suggest Product',
  OrderConfirmation: 'Order Placed',
  Cart: 'Cart',
  AddAddress: 'Add Address',
  AddAddressDetails: 'Add Address Details',
  Payment: 'Payment Methods',
  SingleOrder: 'Single Order Details',
  Categories: 'All Categories',
  Search: 'Search Products Screen',
};
